const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const source = fs.readFileSync(require('node:path').join(__dirname, '../src/lib/validation.ts'), 'utf8');
const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText;
const result = { exports: {} };
new Function('exports', 'module', compiled)(result.exports, result);
const { coreWarnings, extraWarnings } = result.exports;
const core = () => ({ditaksir:true, aktiviti:'KELAB', jawatan:'AHLI AKTIF', pelibatan:[{slot:2,peringkat:'SEKOLAH'}], pencapaian:{peringkat:'SEKOLAH',kedudukan:'JOHAN'}, komitmen:['PILIHAN'], khidmatSumbangan:'SUMBANGAN', kehadiran:0});
const extra = () => ({ditaksir:true,perkhidmatan:null,anugerahKhas:{name:'ANUGERAH',achievement:'PENERIMA'},khidmatMasyarakat:[{activity:'AKTIVITI',count:1}],nilamStars:1});
test('independent slot 2, one commitment and attendance zero are valid',()=>assert.deepEqual(coreWarnings(core()),{}));
test('all eight missing core fields are flagged',()=>assert.equal(Object.keys(coreWarnings({})).length,8));
test('zero attendance valid but empty, null and invalid values are flagged',()=>{for(const value of ['',null,undefined,-1,13,1.5]) assert.ok(coreWarnings({...core(),kehadiran:value}).kehadiran);});
test('commitment maximum is four, not a minimum',()=>{assert.deepEqual(coreWarnings({...core(),komitmen:['A','B','C','D']}),{});assert.ok(coreWarnings({...core(),komitmen:['A','B','C','D','E']}).komitmen);});
test('both achievement fields must be present',()=>{assert.ok(coreWarnings({...core(),pencapaian:{peringkat:'NEGERI'}}).pencapaianKedudukan);assert.ok(coreWarnings({...core(),pencapaian:{kedudukan:'JOHAN'}}).pencapaianPeringkat);});
test('optional extra service and special awards are never flagged or changed',()=>{for(const value of [null,undefined,{}, {label:''}]) {const data={...extra(),perkhidmatan:value,anugerahKhas:value};const before=JSON.stringify(data);assert.deepEqual(extraWarnings(data),{});assert.equal(JSON.stringify(data),before);}assert.deepEqual(Object.keys(extraWarnings({})),['khidmatMasyarakat','nilamStars']);});
test('unassessed sections are exempt',()=>{assert.deepEqual(coreWarnings({ditaksir:false}),{});assert.deepEqual(extraWarnings({ditaksir:false}),{});});
test('extra totals and NILAM bounds',()=>{assert.ok(extraWarnings({...extra(),khidmatMasyarakat:[{activity:'A',count:3},{activity:'B',count:3}]}).khidmatMasyarakat);assert.ok(extraWarnings({...extra(),nilamStars:0}).nilamStars);});
test('validation preserves all original values, metadata and slot numbers',()=>{const c=core(),e=extra();c.metadata={legacy:'preserve'};e.perkhidmatan={label:'LEGACY',score:8};const before=JSON.stringify({c,e});coreWarnings(c);extraWarnings(e);assert.equal(JSON.stringify({c,e}),before);});
