-- PAJSK SKSA isolated storage inside Perjumpaan Kokurikulum SKSA.
-- This source migration mirrors the live migration. It creates only new pajsk_* objects
-- and deliberately does not alter Portal Koku tables or the legacy public.pajsk_records table.

create extension if not exists pgcrypto;
create table if not exists public.pajsk_student_records (
  id uuid primary key default gen_random_uuid(), student_id uuid not null,
  session_year integer not null check (session_year between 2000 and 2100),
  class_id uuid null, class_code text not null default '', class_name text not null default '',
  year_level smallint null check (year_level is null or year_level between 0 and 6),
  myid_cache text not null default '', full_name_cache text not null default '',
  kelab_persatuan jsonb not null default '{}'::jsonb,
  badan_beruniform jsonb not null default '{}'::jsonb,
  sukan_permainan jsonb not null default '{}'::jsonb,
  ekstra_kurikulum jsonb not null default '{}'::jsonb,
  complete boolean not null default false,
  status text not null default 'draft' check (status in ('draft','complete','imported','review')),
  source text not null default 'webapp' check (source in ('webapp','idme_import','legacy','admin')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint pajsk_student_records_student_session_unique unique (student_id,session_year)
);
create table if not exists public.pajsk_settings (key text primary key,value text not null,updated_at timestamptz not null default now());
create table if not exists public.pajsk_audit_log (id bigint generated by default as identity primary key,action text not null,session_year integer,class_code text,student_id uuid,detail jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.pajsk_reference_options (id bigint generated by default as identity primary key,section text not null,code text not null,label text not null,score numeric(6,2),meta jsonb not null default '{}'::jsonb,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(section,code));
insert into public.pajsk_settings(key,value) values ('school_name','SEKOLAH KEBANGSAAN SUNGAI ABONG'),('extension_key_sha256','ad223782eb6ba939cc2e14eff1438d01e557566ec81a2f2242659f9f4cb2a7a9') on conflict(key) do nothing;
insert into public.pajsk_settings(key,value) select 'app_password_sha256',value from public.segak_settings where key='app_password_sha256' on conflict(key) do update set value=excluded.value,updated_at=now();
create index if not exists idx_pajsk_student_records_session_class on public.pajsk_student_records(session_year,class_code);
create index if not exists idx_pajsk_student_records_student on public.pajsk_student_records(student_id);
create index if not exists idx_pajsk_student_records_complete on public.pajsk_student_records(session_year,complete);
create index if not exists idx_pajsk_audit_created_at on public.pajsk_audit_log(created_at desc);
create index if not exists idx_pajsk_reference_options_section on public.pajsk_reference_options(section,active);
create or replace function public.set_pajsk_updated_at() returns trigger language plpgsql set search_path=public as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists trg_pajsk_student_records_updated_at on public.pajsk_student_records;
create trigger trg_pajsk_student_records_updated_at before update on public.pajsk_student_records for each row execute function public.set_pajsk_updated_at();
drop trigger if exists trg_pajsk_settings_updated_at on public.pajsk_settings;
create trigger trg_pajsk_settings_updated_at before update on public.pajsk_settings for each row execute function public.set_pajsk_updated_at();
drop trigger if exists trg_pajsk_reference_options_updated_at on public.pajsk_reference_options;
create trigger trg_pajsk_reference_options_updated_at before update on public.pajsk_reference_options for each row execute function public.set_pajsk_updated_at();
alter table public.pajsk_student_records enable row level security;
alter table public.pajsk_settings enable row level security;
alter table public.pajsk_audit_log enable row level security;
alter table public.pajsk_reference_options enable row level security;
revoke all on public.pajsk_student_records from anon,authenticated;
revoke all on public.pajsk_settings from anon,authenticated;
revoke all on public.pajsk_audit_log from anon,authenticated;
revoke all on public.pajsk_reference_options from anon,authenticated;
