-- Exact SPPB/iDME labels transcribed from screenshots supplied on 2026-10-01.
-- Only labels are asserted here. No score is inferred from the screenshots.

delete from public.pajsk_reference_options where section in ('activity_club','activity_uniform','activity_sport','position_club','position_uniform','position_sport');

with vals(section,ord,label) as (
 values
 ('activity_club',1,'KELAB DOKTOR MUDA (SR)'),('activity_club',2,'KELAB KESELAMATAN JALANRAYA (SR)'),('activity_club',3,'KELAB PENCEGAHAN JENAYAH (SR)'),('activity_club',4,'KELAB RUKUN NEGARA (SR)'),('activity_club',5,'KELAB SAINS, TEKNOLOGI, KEJURUTERAAN DAN MATEMATIK (STEM)/SOLAR (SR)'),('activity_club',6,'PERSATUAN AGAMA ISLAM (SR)'),('activity_club',7,'PERSATUAN BAHASA INGGERIS (SR)'),('activity_club',8,'PERSATUAN BAHASA MELAYU (SR)'),('activity_club',9,'SENI TARI (SR)'),
 ('activity_uniform',1,'BULAN SABIT MERAH MALAYSIA (BSMM) (SR)'),('activity_uniform',2,'KADET REMAJA SEKOLAH (SR)'),('activity_uniform',3,'PERGERAKAN PUTERI ISLAM MALAYSIA (PPIM) (SR)'),('activity_uniform',4,'PERSEKUTUAN PENGAKAP MALAYSIA (SR)'),
 ('activity_sport',1,'BOLA BALING (SR)'),('activity_sport',2,'BOLA JARING (SR)'),('activity_sport',3,'BOLA SEPAK (SR)'),('activity_sport',4,'GASING (SR)'),('activity_sport',5,'KRIKET (SR)'),
 ('position_club',1,'PENGERUSI'),('position_club',2,'NAIB PENGERUSI'),('position_club',3,'SETIAUSAHA'),('position_club',4,'BENDAHARI'),('position_club',5,'NAIB SETIAUSAHA'),('position_club',6,'NAIB BENDAHARI'),('position_club',7,'AHLI JAWATANKUASA'),('position_club',8,'AHLI AKTIF'),('position_club',9,'AHLI BIASA'),
 ('position_uniform',1,'PENGERUSI'),('position_uniform',2,'NAIB PENGERUSI'),('position_uniform',3,'SETIAUSAHA'),('position_uniform',4,'BENDAHARI'),('position_uniform',5,'NAIB SETIAUSAHA'),('position_uniform',6,'NAIB BENDAHARI'),('position_uniform',7,'PEGAWAI WARAN KRS I & II'),('position_uniform',8,'STAF SARJAN KRS'),('position_uniform',9,'SARJAN KRS'),('position_uniform',10,'LANS KOPERAL KRS'),('position_uniform',11,'SARJAN TKRS'),('position_uniform',12,'KOPERAL TKRS'),('position_uniform',13,'LANS KOPERAL TKRS'),('position_uniform',14,'WARAN II'),('position_uniform',15,'STAF SARJAN'),('position_uniform',16,'BINTARA KANAN'),('position_uniform',17,'FLIGHT SARJAN'),('position_uniform',18,'SARJAN'),('position_uniform',19,'SARJAN UDARA'),('position_uniform',20,'KOPERAL'),('position_uniform',21,'LASKAR KANAN'),('position_uniform',22,'KOPERAL UDARA'),('position_uniform',23,'LANS KOPERAL'),('position_uniform',24,'LASKAR MUDA'),('position_uniform',25,'SUB INSPEKTOR'),('position_uniform',26,'SARJAN MEJAR'),('position_uniform',27,'PEGAWAI KADET'),('position_uniform',28,'KETUA BOMBA JUNIOR'),('position_uniform',29,'PENOLONG KETUA BOMBA JUNIOR'),('position_uniform',30,'KETUA PASUKAN'),('position_uniform',31,'PEGAWAI KANAN KADET'),('position_uniform',32,'PEGAWAI WARAN KADET'),('position_uniform',33,'SARJAN KADET'),('position_uniform',34,'KOPERAL KADET'),('position_uniform',35,'LANS KOPERAL KADET'),('position_uniform',36,'TUSPA (SARJAN)'),('position_uniform',37,'TUSPA (KOPERAL)'),('position_uniform',38,'TUSPA (LANS KOPERAL)'),('position_uniform',39,'KETUA TRUP'),('position_uniform',40,'PENOLONG KETUA TRUP'),('position_uniform',41,'KETUA PATROL'),('position_uniform',42,'PENOLONG KETUA PATROL'),('position_uniform',43,'PENGAKAP (KUATERMASTER)'),('position_uniform',44,'KETUA PEK'),('position_uniform',45,'PENOLONG KETUA PEK'),('position_uniform',46,'PENOLONG KETUA SEKAWAN'),('position_uniform',47,'MEGA PUTERI'),('position_uniform',48,'PUTERI MEGASARI'),('position_uniform',49,'PUTERI BISTARIA'),('position_uniform',50,'PUTERI KEJORA'),('position_uniform',51,'PUTERI SAUJANA /KETUA PASUKAN'),('position_uniform',52,'PUTERI MESTIKA'),('position_uniform',53,'KETUA SEKSYEN UTAMA'),('position_uniform',54,'PENOLONG KETUA SEKSYEN'),('position_uniform',55,'KETUA PLATUN'),('position_uniform',56,'PENOLONG KETUA PLATUN'),('position_uniform',57,'SARJAN DEWASA / KETUA KADET'),('position_uniform',58,'LANS KOPERAL DEWASA / KOPERAL KADET'),('position_uniform',59,'BRASS BAND (DRUM MAJOR)'),('position_uniform',60,'BRASS BAND (KETUA SEKSYEN)'),('position_uniform',61,'BRASS BAND (PENOLONG KETUA SEKSYEN)'),('position_uniform',62,'BRASS BAND (KUATERMASTER)'),('position_uniform',63,'AHLI JAWATANKUASA'),('position_uniform',64,'AHLI AKTIF'),('position_uniform',65,'AHLI BIASA'),
 ('position_sport',1,'PENGERUSI'),('position_sport',2,'KAPTEN PASUKAN'),('position_sport',3,'KETUA RUMAH'),('position_sport',4,'NAIB PENGERUSI'),('position_sport',5,'PENOLONG KETUA RUMAH'),('position_sport',6,'PENOLONG KAPTEN'),('position_sport',7,'SETIAUSAHA'),('position_sport',8,'BENDAHARI'),('position_sport',9,'NAIB SETIAUSAHA'),('position_sport',10,'NAIB BENDAHARI'),('position_sport',11,'AHLI JAWATANKUASA'),('position_sport',12,'AHLI AKTIF'),('position_sport',13,'AHLI BIASA'),('position_sport',14,'BENGKUNG MERAH / TALI PINGGANG HITAM'),('position_sport',15,'BENGKUNG HIJAU 3 / TALI PINGGANG MERAH 2'),('position_sport',16,'BENGKUNG HIJAU 2 / TALI PINGGANG MERAH 1'),('position_sport',17,'BENGKUNG HIJAU 1 / TALI PINGGANG BIRU 2'),('position_sport',18,'CULA 3 / TALI PINGGANG BIRU 1'),('position_sport',19,'CLASS 3 / CULA 2 / TALI PINGGANG HIJAU'),('position_sport',20,'TALI PINGGANG KUNING')
)
insert into public.pajsk_reference_options(section,code,label,score,meta,active)
select section,lower(regexp_replace(label,'[^A-Za-z0-9]+','_','g'))||'_'||ord,label,null,jsonb_build_object('order',ord,'source','user_screenshot_2026-10-01'),true from vals;
